# Generated by Django 4.0.5 on 2022-10-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, null=True)),
                ('level', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
